/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Customers;
import control.SalesPersonControl;

/**
 *
 * @author ahmadnasser
 */
public class AsCustomer extends javax.swing.JFrame {

    private Customers customer;
    private SalesPersonControl SPC;
    /**
     * Creates new form AsCustomer
     */
    public AsCustomer(Customers c) {
        
        initComponents();
        customer = c;
        this.message.setText("Welcome " +  customer.getC_FirstName() + "!");
        SPC = new SalesPersonControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message = new javax.swing.JLabel();
        BrowseC = new javax.swing.JButton();
        BrowseSP = new javax.swing.JButton();
        back = new javax.swing.JButton();
        UpdateInfo = new javax.swing.JButton();
        DeleteAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 29, 158, 41));

        BrowseC.setBackground(new java.awt.Color(107, 5, 107));
        BrowseC.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BrowseC.setText("Browse Cars");
        BrowseC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseCActionPerformed(evt);
            }
        });
        getContentPane().add(BrowseC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 117, 154, 56));

        BrowseSP.setBackground(new java.awt.Color(107, 5, 107));
        BrowseSP.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BrowseSP.setText("Browse Sales People");
        BrowseSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseSPActionPerformed(evt);
            }
        });
        getContentPane().add(BrowseSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 117, -1, 56));

        back.setBackground(new java.awt.Color(107, 5, 107));
        back.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 254, -1, -1));

        UpdateInfo.setBackground(new java.awt.Color(107, 5, 107));
        UpdateInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        UpdateInfo.setText("Update My Info");
        UpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 254, -1, -1));

        DeleteAccount.setBackground(new java.awt.Color(107, 5, 107));
        DeleteAccount.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DeleteAccount.setText("Delete My Account");
        getContentPane().add(DeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 254, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/car.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseCActionPerformed

        BrowseCars BC = new BrowseCars(customer);
        BC.setVisible(true);

    }//GEN-LAST:event_BrowseCActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
               dispose();
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void UpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateInfoActionPerformed

    private void BrowseSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseSPActionPerformed
           BrowseSalesPerson BSP = new BrowseSalesPerson (this.SPC.getAllSalesPeople());
          BSP.setVisible(true);
    }//GEN-LAST:event_BrowseSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsCustomer(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseC;
    private javax.swing.JButton BrowseSP;
    private javax.swing.JButton DeleteAccount;
    private javax.swing.JButton UpdateInfo;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
