/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.SalesPerson;
import control.CustomerControl;
import javax.swing.JFrame;

/**
 *
 * @author ahmadnasser
 */
public class AsSalesPerson extends JFrame{

    private SalesPerson SP;
    private CustomerControl CC;
    /**
     * Creates new form AsSalesPerson
     */
    public AsSalesPerson(SalesPerson SP) {
        initComponents();
        this.SP = SP;
        this.message.setText("Welcome " + this.SP.getSP_FirstName() + "!");
        CC = new CustomerControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        message = new javax.swing.JLabel();
        browseCustomers = new javax.swing.JButton();
        UpdateInfo = new javax.swing.JButton();
        back = new javax.swing.JButton();
        DeleteAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 176, 22));

        browseCustomers.setBackground(new java.awt.Color(107, 5, 107));
        browseCustomers.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        browseCustomers.setText("Browse Customers");
        browseCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(browseCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 145, 43));

        UpdateInfo.setBackground(new java.awt.Color(107, 5, 107));
        UpdateInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        UpdateInfo.setText("Update My Info");
        UpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 145, 42));

        back.setBackground(new java.awt.Color(107, 5, 107));
        back.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        DeleteAccount.setBackground(new java.awt.Color(107, 5, 107));
        DeleteAccount.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DeleteAccount.setText("Delete My Account");
        getContentPane().add(DeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 145, 43));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/car.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCustomersActionPerformed
        //dispose();
        BrowseCustomers BC = new BrowseCustomers(this.CC.getAllCustomers());
        BC.setVisible(true);
    }//GEN-LAST:event_browseCustomersActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void UpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoActionPerformed
        this.setVisible(false);
        UpdateMyInfo up= new UpdateMyInfo(SP);
        up.setVisible(true);
    }//GEN-LAST:event_UpdateInfoActionPerformed
public void S_UpdateMyInfo(java.awt.event.ActionEvent evt){

}
public void DeleteMyAccount(java.awt.event.ActionEvent evt){

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsSalesPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsSalesPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsSalesPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsSalesPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsSalesPerson(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteAccount;
    private javax.swing.JButton UpdateInfo;
    private javax.swing.JButton back;
    private javax.swing.JButton browseCustomers;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
