/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.SalesPerson;
import control.SalesPersonControl;

/**
 *
 * @author user
 */
public class UpdateMyInfo extends javax.swing.JFrame {
 SalesPersonControl SPCtrl=new SalesPersonControl();
SalesPerson sp;
 /**
     * Creates new form UpdateMyInfo
     */
    public UpdateMyInfo(SalesPerson sp) {
//      sp=new SalesPerson();
        this.sp=sp;
        initComponents();
        this.firstName.setText(sp.getSP_FirstName());
        this.lastName.setText(sp.getSP_LastName());
        this.phoneNumber.setText(""+sp.getSP_PhoneNumber());
        this.email.setText(sp.getSP_Email());
        this.yearOfExp.setText(""+sp.getYearsOfExperience());
    }
     public UpdateMyInfo() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        YearsOfExp = new javax.swing.JLabel();
        yearOfExp = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        wrong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 96, 180, -1));

        FirstName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        FirstName.setText("First Name:");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 73, 81, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 159, -1, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 165, 180, -1));

        YearsOfExp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        YearsOfExp.setText("Years Of Experience:");
        getContentPane().add(YearsOfExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 203, -1, -1));

        yearOfExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearOfExpActionPerformed(evt);
            }
        });
        getContentPane().add(yearOfExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, -1));

        LastName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        LastName.setText("Last Name:");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 73, 82, -1));
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 96, 180, -1));

        PhoneNumber.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PhoneNumber.setText("Phone Number:");
        getContentPane().add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 142, 180, -1));
        getContentPane().add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 165, 180, -1));

        Email.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 142, 61, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Update My Info");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 148, 44));

        Submit.setBackground(new java.awt.Color(107, 5, 107));
        Submit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 225, 107, 47));

        Back.setBackground(new java.awt.Color(107, 5, 107));
        Back.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 302, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pov-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 650, 330));

        wrong.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

                this.sp.setSP_FirstName(firstName.getText());
                this.sp.setSP_LastName(lastName.getText());
                this.sp.setSP_PhoneNumber(Integer.parseInt(this.phoneNumber.getText()));
                this.sp.setSP_Email(email.getText());
                this.sp.setYearsOfExperience(Integer.parseInt(this.yearOfExp.getText()));
                
                int status = SPCtrl.S_UpdateMyInfo(sp);
                if (status == 0){
                    this.setVisible(false);
                    ChangesSaved CS = new ChangesSaved(sp);
                    CS.setVisible(true);
                }
                else {
                    System.out.println(status);
                    this.wrong.setText("Wrong email format.");
                }
       
    }//GEN-LAST:event_SubmitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void yearOfExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearOfExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearOfExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMyInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel YearsOfExp;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JLabel wrong;
    private javax.swing.JTextField yearOfExp;
    // End of variables declaration//GEN-END:variables
}
